"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var cors_1 = require("cors");
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
var apiRouter = express_1.default.Router();
var image_1 = require("./image");
apiRouter.use('/images', image_1.imageRouter);
exports.default = apiRouter;
